### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by Californ1a** [felhag/lastfm-stats-web#10]
I have a lot of scrobbles, and every time I go to the page it has to re-scan my entire list of scrobbles which takes at least 5min. It also makes me not want to share the link with others, if they'll have to sit there waiting for it to load all my scrobbles after I already did that waiting before sending them the link.

It wouldn't solve the link sharing issue, but even just an option to save a client-side cache in IndexedDB so it doesn't take so long on future visits would be great; just get the changes from the last visit rather than the entire scrobble list again.

**Comment by felhag** [comment]
Yeah, I agree. Implementing indexedDB has been mentioned a few times before and is one of the first improvements to build I think. Might be even better to save the loaded scrobbles somewhere in the cloud (which could solve your sharing issue) but I don't think i'll go that far. 

Do you use the import/export to json/csv functionality? At least it prevents the long loading time for you. Sharing is still not very trivial since you would have to pass around files.

**Comment by Californ1a** [comment]
> Do you use the import/export to json/csv functionality?

Not currently, because I prefer to directly bookmark the URL for my profile rather than the homepage. It would be a bit of a hassle to have to go to the homepage and browse to a file every time, though I guess it would ultimately be faster than waiting on the scan so maybe I'll start doing that instead.

Looking at the json export now, it seems like IndexedDB would be the way to go for client-side storage - rather than `username` and `scrobbles` keys, have a table for each username you view, and store the scrobbled array in there. I know the vanilla idb API is pretty annoying to work with though - I've used [Dexie](https://dexie.org/) on a Vue project recently, but I've got no experience with Angular.

Ideally it would be a cloud solution so you could share the direct link without needing a bunch of extra requests, but at least idb would be a good stopgap between manually loading a file and having full cloud storage. Something like Firebase might work if it's just a big json array.

**Comment by felhag** [comment]
Looks like Dexie is compatible with Angular, seems like the best option at first sight. It might take a while before I have time to start with this though.

**Comment by felhag** [comment]
Just released 5.0 including support for indexedDB. I'll close the issue!
