### ISSUE TITLE
The claimed number of times I've scrobbled some tracks in 2022 on a given day is exactly double what it should be

### ISSUE THREAD

**Issue by BDR159** [felhag/lastfm-stats-web#28]
But the total number of scrobbles is still correct.

**Comment by felhag** [comment]
Thanks for creating the issue! Similar issues have been mentioned on Reddit a few times as well. Haven't had time to look further into it, but could you specify a little more where the issue occurred (which tab, which list etc)?

**Comment by felhag** [comment]
I think this is solved in version 5.3. If not; please reopen with some additional information.
