### ISSUE TITLE
[request] ability to change date format

### ISSUE THREAD

**Issue by RememberTheAir** [felhag/lastfm-stats-web#29]
Hello,

First off, thanks for the great website! I really love to check it out every once in a while.

There's just one thing that I find a little distracting/weird: the date format is MM/DD/YYYY, which is a little confusing if you live in a country that doesn't use this format. Would it be possible to make it follow your browser/machine settings? Or make it configurable?

Thanks!

**Comment by felhag** [comment]
Hey, thanks for creating the issue. The date format should already be based on your browser settings. For example San Fransisco shows 12/17/2009 and Amsterdam shows 28-12-2022. Do you not which locale settings you're using?

**Comment by RememberTheAir** [comment]
You are right, just changed Firefox's language to Italian and the date format changed accordingly. Thanks :D
