### ISSUE TITLE
Arrow toggle on race chart

### ISSUE THREAD

**Issue by blakegearin** [felhag/lastfm-stats-web#3]
The design of the arrows to toggle seconds on the race chart is a bit confusing. Intuitively I would expect the left arrow to slow things down and the right to do the opposite. While this is the case, the number getting bigger makes me think it's getting faster. I'm not sure how this could be improved, but here are a few ideas.

1. Make the icons up or down arrows like Reddit instead of resembling reverse and fast forward
2. Instead of displaying the seconds between each month, show the total duration of the "video"/graphic
3. Move away from seconds per month instead using a video/podcast-like system where `x1.0` speed is 1s/month and the arrows toggle it to be slower/faster (e.g. `0.5`, `1.0`, `1.5`, `2.0`, etc)

**Comment by felhag** [comment]
Thanks for your suggestion! I agree it's not very intuitive. I think a combination of 1 and 3 could be nice solution. Maybe the scale could be an issue though, since I only tend to slow it down and speed would be a small number.

**Comment by felhag** [comment]
Added an improvement for this issue in the latest version.
