### ISSUE TITLE
Request: Please have the tooltips close automatically

### ISSUE THREAD

**Issue by thereddestdog** [felhag/lastfm-stats-web#30]
Instead of having to click 'Got it!' to close these tooltips, can you have them auto-dismiss after a few seconds or close by clicking the "i" icon again, kinda like a toggle? 

![image](https://user-images.githubusercontent.com/24947579/209201419-d3f59b71-7772-4c1c-967e-1a5232f7d9d5.png)

Thanks!

**Comment by felhag** [comment]
Of course :) I think it even is the default behaviour for the material snackbar component. I explicitly disabled the auto-dismiss because it can contain quite some text which can be hard to read in a few seconds. The toggle sounds nice though.
