### ISSUE TITLE
[Feature Request] Collage Generation

### ISSUE THREAD

**Issue by VelocityRa** [felhag/lastfm-stats-web#31]
Something like:
* https://www.tapmusic.net/
* https://lastcollage.io

The above options either lack in certain features, are outdated/unmaintained and/or closed-source.

---
Thanks for your work on this project btw! I appreciate all the cool ideas for stats. And for open-sourcing it.
Was actually thinking of making something similar lately but I'm not big on web stuff, and you did a much better job than I could :)

**Comment by felhag** [comment]
Hey, thanks for creating the ticket, nice to hear you like the site :). But I think at the moment something like collage generation doesn't really fit the tool. Besides the ones you mentioned seem to work fine (although there might be room for improvement etc).

**Comment by VelocityRa** [comment]
Okay! Thank you for taking the time to respond.
