### ISSUE TITLE
[FEATURE REQUEST] Artists race chart is an image

### ISSUE THREAD

**Issue by iHestia** [felhag/lastfm-stats-web#33]
Currently the Artists race chart is just one image when downloaded, I would love for it to be a gif or video when downloaded, it's one of the coolest things on the website and being able to share it with friends would be dope!

**Comment by felhag** [comment]
I agree, this would be a really cool feature but I'm afraid its really difficult to implement as well... I'll try to look into it.

**Comment by felhag** [comment]
The charting library which i'm using does not support this unfortunately. I think you'll have to use a screen recorder like OBS to solve this issue.
