### ISSUE TITLE
Dataset page not working

### ISSUE THREAD

**Issue by mdn522** [felhag/lastfm-stats-web#36]

**Comment by BDR159** [comment]
I can confirm the issue as well
<img width="1196" alt="image" src="https://github.com/felhag/lastfm-stats-web/assets/60425968/62c9e207-44e4-489e-9e41-7fe6cc63cab5">

**Comment by felhag** [comment]
Ouch.. Updated to Angular 16 a few days ago, that's probably the culprit. I'll try to have a look at it next week. Thanks for reporting the issue though.
