### ISSUE TITLE
Wrong album artist

### ISSUE THREAD

**Issue by IAmDitzyDoo** [felhag/lastfm-stats-web#4]
Hello there,
I got issue with albums stats, because I have many artists with songs in like one big album by one record label. Unfortunately, some albums are shown by multiple artists instead which is not showing correctly.

To show my I mean, I have albums released by record label NoCopyrightSounds - NCS: Infinity, NCS: The Best of 2015 etc. they are shown not by the record label, but by artists with the songs with the album, which can lead to misunderstanding.

I hope this can be fixed. If you want to be sure, you can check my profile what I mean [here](https://www.last.fm/user/IzzyMailmare/library/music/NoCopyrightSounds) - I have just albums & no scrobbles, because they're just releasing only albums & not songs.

**Comment by felhag** [comment]
Hey hey, it is a known issue but I'm afraid it's pretty difficult to fix. I'm using [this endpoint](https://www.last.fm/api/show/user.getRecentTracks) to retrieve all scrobbles. It provides an artist and an album name but it doesn't give additional information about the album. This means I would have to make another request for each scrobble (or at least for each album) to retrieve this information which would really slow down the loading process. 

I have some ideas to create an integration with MusicBrainz or something similar which could solve this issue as well.. But I don't think I have time to implement this in the short term.

**Comment by felhag** [comment]
Closed due inactivity and probably won't be fixed soon because of the technical setup.
