### ISSUE TITLE
spotifystats.app: zip file from spotify no longer works

### ISSUE THREAD

**Issue by BDR159** [felhag/lastfm-stats-web#45]
The reason it no longer works is because the folder (after unzipping) is now called `Spotify Extended Streaming History` (or whatever the yearly one is called) instead of `MyData`. When I change it back to `MyData` it works. This has been the case since December 15 at the latest when I last requested my data.

**Comment by felhag** [comment]
Oh man, they changed it again? :/ I'll have a look at it asap.

**Comment by felhag** [comment]
Sorry for the delay, should be fixed now.
