### ISSUE TITLE
pheelix.dev is down

### ISSUE THREAD

**Issue by Colon101** [felhag/lastfm-stats-web#46]
spotify stats fetches for pheelix.dev but it gets 502 ngnix is configured incorrectly probably lol

**Comment by felhag** [comment]
You're right, server is moved and I haven't bothered fixing it yet. I'll try to adjust it next time i'm working on the project.

**Comment by Colon101** [comment]
whats the new domain ill make a pull request

**Comment by felhag** [comment]
The domain is the same, the server physically moved since I moved as well :P. So I have to reconfigure nginx and my router again. But I think I'll just remove the Matomo connection completely since I haven't checked it in ages anyways.

**Comment by felhag** [comment]
Fixed the nginx config :)
