### ISSUE TITLE
Artist dataset sorting issue

### ISSUE THREAD

**Issue by fizmatbfu** [felhag/lastfm-stats-web#48]
Hi.
It is not entirely clear why sometimes in the list of artists the number of scrobbles is not in descending order. Is this how it should be?

Some examples:
![изображение](https://github.com/felhag/lastfm-stats-web/assets/36421069/355b9f14-8eca-44d0-aa40-8fdc070a232b)

![изображение](https://github.com/felhag/lastfm-stats-web/assets/36421069/c7b1a88f-1f59-478d-84b0-b8a1c1f9e736)

![изображение](https://github.com/felhag/lastfm-stats-web/assets/36421069/9fcaeada-b124-4ede-a2d0-722f47388680)

Thanks for answer.

**Comment by felhag** [comment]
If I had to guess i'd say it's not taking the current month into account. For example based on your first image I think you listened to "Fawn" 5 times since 1 april. Could you verify this for me?

**Comment by felhag** [comment]
Just released a fix for this issue (by including the current month when determining the rank), could you let me know if it solves your issue?
