### ISSUE TITLE
Where did the ordering of all artists/albums/tracks by the order of their first listen go?

### ISSUE THREAD

**Issue by Violetic8** [felhag/lastfm-stats-web#49]
I don't mind the newest change of being able to sort monthly things and having them updated as the month goes on, but I feel like it took away a feature I liked: being able to turn off all sorting and have the artists/albums/tracks listed in the order of me first adding them to my library. It just defaults to my current top.

For reference - this is how, indeed, my top artists by scrobbling amount looks like:

![image](https://github.com/felhag/lastfm-stats-web/assets/166140349/b97470cc-0eb2-4316-886b-8f410d3e611c)

And this is when I unsort it (no arrow going up at the "Rank" section):

![image](https://github.com/felhag/lastfm-stats-web/assets/166140349/05f3af40-de5e-4bda-ba02-428d4b70a7b7)

Would it be a possibility for this to be brought back?

**Comment by felhag** [comment]
I didn't intentionally remove it, just wasn't aware it used to work this way. So you say before the recent changes the unsorted dataset was order by date it was added to your lastfm library? I'll see if I can bring it back, or maybe I could even add an extra column for this date.
