### ISSUE TITLE
In all sections only position 1 is displayed

### ISSUE THREAD

**Issue by Pinker75** [felhag/lastfm-stats-web#52]
It just so happens that I had to re-collect LastFM's stats for all time. After that, in all tabs and in all sections I see only position 1. At the same time, the DataSet contains full information.

![2024-05-05_12-44-34](https://github.com/felhag/lastfm-stats-web/assets/168963296/263f63ee-7331-4c9b-95da-10d8858e5a42)
![2024-05-05_12-44-45](https://github.com/felhag/lastfm-stats-web/assets/168963296/b2647f63-0368-4491-b2e0-3b80b3c8dfc7)
![2024-05-05_12-44-55](https://github.com/felhag/lastfm-stats-web/assets/168963296/36798135-1ab8-4d9e-ab02-e65b5ddfb559)
![2024-05-05_12-45-07](https://github.com/felhag/lastfm-stats-web/assets/168963296/267cadad-6593-41ac-b87e-55e09c29c2e8)

**Comment by felhag** [comment]
It looks like the list size is set at 1. This can be configured with the slider in the top with the Filter data dialog.

**Comment by Pinker75** [comment]
Oh, my God, really! I never noticed that slider. Thank you!
