### ISSUE TITLE
Scale and timeframes

### ISSUE THREAD

**Issue by agisXIV** [felhag/lastfm-stats-web#55]
Love all the data, just a couple small suggestions
1: The dataset page is great, but due to the nature of the scale a lot of the information is really hard to read - especially rank. If it could be logarithmic that would make it so much easy to see the important differences (1-50 is often obscured because if you scrobbled a track just once or twice in a month before getting into it later, all you can see is when it climbs so many thousand places to go from 1-3 scrobbles)

2: the race chart and cumulative are also super cool, but if you could set them to past year/6 months etc instead of being locked into 'all time', would be much appreciated

**Comment by felhag** [comment]
Hey! Thanks for creating the issue. Making the graph for the rank logarithmic makes sense imho. I'll might add this in the next release.

Regarding point 2, you can use the 'Filter data' button to adjust the timeframe. I think this should also apply for the charts!
