### ISSUE TITLE
User library links render error 500

### ISSUE THREAD

**Issue by Row** [felhag/lastfm-stats-web#57]
Perhaps there is an issue on Last.fm's side as well.

It seems that if the username's case (whether the letters are uppercase or lowercase) is incorrect, it results in a 500 error.

My username is 'Rowolta', not 'rowolta.'

The broken link looks like this: https://www.last.fm/user/rowolta/library/music/Misery%20Index
The correct link should be: https://www.last.fm/user/Rowolta/library/music/Misery%20Index

A solution could be to use the username provided by the API to ensure the correct casing?

**Comment by felhag** [comment]
Hey! Thanks for reporting the issue but I'm not able to reproduce it yet. When do you get this error? If the page is loading or when you click on an item in on of the lists? It seems to work fine for me when using the lower case version of your username.

**Comment by Row** [comment]
Do you have uppercase in your username? Perhaps it is only when viewing your own profile.

**Comment by felhag** [comment]
No, unfortunately my username is fully lower cased. But I loaded your username into the website and didn't ran into any issues. When does the error occur for you? And do you use any import/export functions like saving your data into the browser? 

It might be an issue with the amount of scrobbles on your account as well. No sure where the turning point is, but the last fm api seems to get a little wobbly for larger account (see #56 for example). I added some fallback scenario's if an error is returned by the api by reducing the page size. This seems to work fine with my own account (~200k scrobbles) but your account has a lot scrobbles so the solution might not be sufficient.

**Comment by Row** [comment]
The only problem is the links in the GUI. Site seems to be working fine on my phone. This is on OS X using the browser database alternative.

See attached screen recording.

https://github.com/user-attachments/assets/9dac940f-eb6e-447d-b3d7-ba8c1867d10c

**Comment by felhag** [comment]
That's weird.. That exact link doesn't give any issues on my browser (tried with Firefox and Chrome on Windows). Really no clue why a browser would change the behavior in this case. 

Anyway, I'll see if I can use the username provided by the api response for building the urls.
